<?php

define('UNIAUTH_ERROR_INVALID_SERVERVARS',100);
define('UNIAUTH_ERROR_NO_SESSION',101);
define('UNIAUTH_ERROR_SOURCE_NOT_EXIST',102);
define('UNIAUTH_ERROR_SOURCE_NOT_APPLY',103);
define('UNIAUTH_ERROR_DEST_NOT_EXIST',104);
define('UNIAUTH_ERROR_TRANSFER_FAILED',105);
define('UNIAUTH_ERROR_MISSING_REDIRECT',106);
define('UNIAUTH_ERROR_MISSING_UNIAUTH_PARAM',107);
